### ISSUE TITLE
License definition.

### ISSUE THREAD

**Issue by rafaga** [HaikuArchives/Vision#48]
This repo doesn't have a clear license implementation, maintainer please select a license (with preference something GPL-compatible) to make viable some future contributions.

**Comment by scottmc** [comment]
Invalid. License is clearly marked as MPL.  Closing.

**Comment by kallisti5** [comment]
Actually... it isn't *super* clear from the repo what license Vision is released under.
Maybe add a LICENSE file with the contents from http://www.mozilla.org/MPL/ being mindful of MPL 2.0 vs 1.1?

**Comment by kallisti5** [comment]
Ah! It's under "dist"

https://github.com/HaikuArchives/Vision/blob/master/dist/LICENSE

Simply moving it to the root would solve most issues. That's also where github expects the license documents to be for identification purposes.

**Comment by kallisti5** [comment]
Not really.  Converting licenses is a pain.  GPL really shouldn't be a requirement for most to contribute :-)  MPL is still an open source license (as is MIT).  They're both GPL compatible from a relationship standpoint.  Using MIT / MPL code in GPL code doesn't invalidate the GPL (since MPL and MIT are more permissive than GPL)

**Comment by rafaga** [comment]
I see the reference in FSF and says it is not compatible ... http://directory.fsf.org/wiki/License:MPLv1.1

**Comment by kallisti5** [comment]
Ah. Notes say 1.1 isn't compatible.   2.0 might be?

Beyond a licensing theological exercise, are you looking to include Vision sources in a GPL project? Us contacting authors circa 15 years ago to relicense when most of the Haiku folks  (myself included) don't like GPL is a tough sell :-)

This issue is getting off-topic. We *should* move dist/LICENSE into / to make it more accessible.

**Comment by rafaga** [comment]
MPL 2.0 it is compatible

**Comment by scottmc** [comment]
Looking at the Vision recipe on Haikuports I don't see it linking any GPL code, so we have no issue here.  If you'd like to add some cool new feature that would require GPL code, then I'd suggest finding a non-GPL alternative library.  The viral nature of the GPL is off-putting to many developers.
We will keep this issue open until we can get the LICENSE file copied to the root, as it will then show up properly on github.  Switching to MPL 2.0 may be an option, but would require the sign off and all previous developers of Vision.

**Comment by scottmc** [comment]
fixed in f9e8ccd
